import { Metadata } from "next";
import { notFound } from "next/navigation";
const MENU_URL = process.env.MENU_URL!;

export async function generateStaticParams() {
	const menuProducts: T_pizzas = await fetch(MENU_URL).then((res) => res.json());
	return menuProducts.map((pizza) => ({ origin_id: pizza.origin_id.toString() }));
}

export async function generateMetadata({ params }: PizzaPageProps): Promise<Metadata> {
	const { origin_id } = params;
	const response = await fetch(MENU_URL + "/" + origin_id, { next: { revalidate: 3600 } });
	if (response.status === 404) return notFound();
	const pizza: T_pizza = await response.json();

	return {
		title: pizza.title,
		description: "Generated by create next app",
		icons: {
			icon: "/icons/favicon.ico",
			apple: "/icons/apple-touch-icon.png",
		},
	};
}

export default function PizzaLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className="max-w-7xl mx-auto bg-custom-white flex flex-col items-center gap-5 p-5 pb-10 max-sm:p-3 max-sm:pb-6 max-sm:gap-3">
			{children}
		</main>
	);
}
