import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Cart",
	description: "Generated by create next app",
	icons: {
		icon: "/icons/favicon.ico",
		apple: "/icons/apple-touch-icon.png",
	},
};

export default function CartLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return <main className="max-w-7xl mx-auto bg-custom-white">{children}</main>;
}
