import { Header } from "@/components";
import StoreProvider from "@/components/providers/StoreProvider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const nunito = localFont({
	src: "../../public/fonts/Nunito-VariableFont_wght.ttf",
	variable: "--font-family-nunito",
});

export const metadata: Metadata = {
	title: "Next Pizza",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={nunito.className}>
				<StoreProvider>
					<Header />
					{children}
				</StoreProvider>
			</body>
		</html>
	);
}
