import { Header } from "@/components";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const openSans = localFont({
	src: "../../public/fonts/OpenSans-VariableFont_wdth,wght.ttf",
	variable: "--font-family-open-sans",
});

export const metadata: Metadata = {
	title: "Next Pizza",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={openSans.className}>
				<Header />
				{children}
			</body>
		</html>
	);
}
