import { Header } from "@/components";
import StoreProvider from "@/components/providers/StoreProvider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const nunito = localFont({
	src: "../../public/fonts/Nunito-VariableFont_wght.ttf",
	variable: "--font-family-nunito",
});

export const metadata: Metadata = {
	title: {
		template: "%s | Next Pizza",
		default: "Menu | Next Pizza",
	},
	description: "Generated by create next app",
	icons: {
		icon: "/icons/favicon.ico",
		apple: "/icons/apple-touch-icon.png",
	},
};

export default function RootLayout({ children, modal }: Readonly<RootLayoutProps>) {
	return (
		<html lang="en">
			<body className={nunito.className}>
				<StoreProvider>
					<Header />
					{children}
					{modal}
				</StoreProvider>
			</body>
		</html>
	);
}
